# Generated by Django 3.1.12 on 2024-12-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20241222_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('EnG', 'Electronics & Gadgets'), ('FnA', 'Fashion & Apparel'), ('HnL', 'Home & Living'), ('BnP', 'Beauty & Personal Care'), ('SnF', 'Sports & Fitness'), ('BnS', 'Books & Stationery'), ('TnG', 'Toys & Games'), ('HnW', 'Health & Wellness'), ('KnD', 'Kitchen & Dining'), ('JnA', 'Jewelry & Accessories')], max_length=3),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
